### ISSUE TITLE
ažuriranje imenika tijela javne vlasti

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati#53]
### Actual behavior
Na popisu TJV imamo prekršajne sudove koji su s početkom 2019. ukinuti
https://imamopravoznati.org/body/list/all?utf8=%E2%9C%93&public_body_query=prekr%C5%A1aj&commit=Pretra%C5%BEite

### Steps to reproduce
Imenik PristupInfo ima samo tri prekršajna suda
https://tjv.pristupinfo.hr/?search=prekr%C5%A1aj

### Expected behavior
Možemo li napraviti automatsko ažuriranje promjena s imenika PristupInfo?

**Comment by schlos** [comment]
Task is in progress

**Comment by schlos** [comment]
Done - updated this week (automation in progress)
