### ISSUE TITLE
Bolje objasniti Upload dokumenata podnositelja zahtjeva (žalbi, riješenja) 

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati#54]
### Actual behavior
Odgovore koji nisu poslani putem platforme nego poštom ili na e-mail adresu podnositelja zahtjeva korisnik mora opisivati

### Steps to reproduce
n/a

### Expected behavior
Pregledniji status zahtjeva
~~Omogućiti upload dokumenata vezanih za zahtjev od strane podnositelja~~
Bolje objasniti Upload dokumenata podnositelja zahtjeva (žalbi, riješenja)

**Comment by schlos** [comment]
### Actual behavior

http://imamopravoznati.org/help/requesting#offsite

## Kako mogu dodati zahtjeve poslane drugim načinima na ovu stranicu?

Imamo pravo znati arhivu zahtjeva koji su podneseni putem ove internetske stranice te nema za cilj sadržavati arhivu svih zahtjeva za pristup informacijama. Nećemo podržati dodavanje drugih zahtjeva poglavito zato što ne bismo bili u mogućnosti provjeriti jesu li odgovori na njih zaista došli od tijela javnih vlasti. Ako vam je navedeno iznimno važno, uvijek možete poslati isti zahtjev putem stranice Imamo pravo znati.

Related: 
* Authority answered, but not on WDTK https://github.com/mysociety/alaveteli/issues/4802

**Comment by schlos** [comment]
Pitanje koje treba odgovoriti:
* koja je korist od rucnog dodavanja zaprimljenih odogvora koje TJV nije dostavilo putem IPZ email adrese predvidjene za zaprimanje odgovora?
* hipotetski, ako je funkcionalnost dodana, hoce li je korisnici znati koristiti?
* kako regulirati i kontrolirati sto je korisnik uplodao? --> dodatan napor za moderatore i administratore portala jer ce morati pregledavati priloge koje su korisnici uplodali
* nemoguce je dozvoliti samo jednu vrstu sadrzaja a drugu ne (tj. hoce li korisnici uplodati samo sluzbene zaprimljene dokumente?)

**Comment by schlos** [comment]
Misljenja sam da bismo trebali zadrzati postojece funkcionalnosti i kroz bolja objasnjenja na stranici uputiti korisnike da odgovor zaprimljen mimo IPZ mogu uplodati na cloud i u komenaru objaviti zaprimljeni odgovor.

@MeliSkeli sto ti mislis?

**Comment by MeliSkeli** [comment]
Slažem se

**Comment by schlos** [comment]
Issue moved to frontend theme repository for easier tracking: https://github.com/codeforcroatia/imamopravoznati-theme/issues/91
