### ISSUE TITLE
Campaigns micro page

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#61]
### Actual behavior

n/a

Related:
* Add campaign pages - https://github.com/mysociety/alaveteli/issues/1367
* Collect ideas for raising the level of traffic and transactions on existing sites - https://github.com/mysociety/alaveteli/issues/2978

### Expected behavior

Ability to setup micro page for campaigns actions and to track campaign progress.
It could be also a WP page with blog RSS linking to WP campaigns.

See example: 
* Froide by OKFN - https://fragdenstaat.de/
* Action page - https://fragdenstaat.de/aktionen/zensurheberrecht-2019/

Screenshot: 
https://qsnapnet.com/snaps/avyumm4nn7h

![Zensurheberrecht 2019 - FragDenStaat](https://user-images.githubusercontent.com/1014134/60381286-70160d80-9a52-11e9-9cfc-da4aa2925034.jpg)

Screenshot in English (with Google Translate):
https://qsnapnet.com/snaps/jd8fmnvufkh

**Comment by garethrees** [comment]
MuckRock have also been experimenting with "Assignments" pages https://www.muckrock.com/news/archives/2019/apr/18/mueller-report-crowdsource/

**Comment by schlos** [comment]
Solved with experimental functionality Projects:
https://www.mysociety.org/2020/07/24/whatdotheyknow-projects/

(available in v0.39.x.x)
