### ISSUE TITLE
Add canned requests and responses for users

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#70]
### Expected behavior

Add canned requests & canned responses to text boxes.

Canned requests:
* template for "pravo na pristup informacijama"
* template for "pravo na ponovnu uporabu informacija"

Canned responses:
* postal address is not necessary to deliver answer
* send additional clarification to authority
* request missing / remaining info after partial response from authority
* send "pozurnica" (see workflow for internal review)
* etc

**Comment by schlos** [comment]
For responses in a particular situations, see also:
https://www.mysociety.org/2021/06/25/a-tool-to-help-challenge-foi-refusals-now-on-whatdotheyknow/

Snippets functionality on WDTK (needs to be enabled via `AlaveteliFeatures.backend.enable :refusal_snippets`)

Help:
https://github.com/mysociety/whatdotheyknow-theme/tree/master/config/refusal_advice

Exceptions:
https://github.com/mysociety/whatdotheyknow-theme/blob/757ffa221aead059b070b591f8cb85a80080a2d2/lib/model_patches.rb#L49-L58

Edit theme:
https://github.com/mysociety/whatdotheyknow-theme/blob/549459988e9d70c1abf3d93ec75ba5e1d1fb0591/lib/views/help/unhappy.html.erb#L216

**Comment by garethrees** [comment]
You may also be interested in [this blog post](https://www.mysociety.org/2016/12/19/alaveteli-for-campaigners-how-to-create-pre-written-requests-for-your-supporters/) about pre-filled requests.

**Comment by schlos** [comment]
Closing here, as it will be handled via theme ticket (see https://github.com/codeforcroatia/imamopravoznati-theme/issues/77)
