### ISSUE TITLE
Naslovnica: link Saznajte više o Zakonu

### ISSUE THREAD

**Issue by MeliSkeli** [codeforcroatia/imamopravoznati#72]
### Actual behavior
Link ima stare materijale, treba ga updejtati
### Steps to reproduce
Podnaslov: Pravo na pristup informacijama jedno je od ključnih instrumenata svakodnevne borbe protiv korupcije putem transparentnosti te povećanja razine integriteta i odgovornosti demokratskih institucija svih razina vlasti.
Vodič za građane: Korak po korak vodi korisnike kroz zakonsku proceduru do ostvarenja prava na pristup informacijama koje im je i Ustavom zajamčeno. + novi link https://www.pristupinfo.hr/wp-content/uploads/2018/10/KORAK-PO-KORAK-OSTAVRI-SVOJE-PRAVO-NA-INFORMACIJU.pdf
Priručnik za službenike - zamjeniti s Vodič za medije i udruge: Namijenjen novinarima svih medija i udrugama civilnog društva za što efikasniji i kvalitetniji pristup javnim informacijama. + link https://www.pristupinfo.hr/wp-content/uploads/2018/10/esf-vodic_web.pdf
Više informacija: Ustav Republike Hrvatske jamči pravo na pristup informacijama koje posjeduju tijela javne vlasti, a ovo pravo uređeno je zakonima i podzaknskim aktima. + link trenutno ne vodi nikuda, a mogao bi voditi na stranicu PristupInfo Pravni okvir https://www.pristupinfo.hr/pravni-okvir/
### Expected behavior
Ažurirani podaci

**Comment by schlos** [comment]
@MeliSkeli mozes li nam poslati te nove materijale u doc formatu?

**Comment by schlos** [comment]
Materijali se nalaze na http://publikacije.imamopravoznati.org/ --> repozitorij: https://github.com/codeforcroatia/imamopravoznati-publikacije

**Comment by MelisaS** [comment]
oj, misliš baš doc format, ne pdf pretpostavljam?

**Comment by schlos** [comment]
@MelisaS @MeliSkeli imas li to 2 accounta?
Da, doc ili neki drugi strojno citljiv oblik.

**Comment by schlos** [comment]
Mozes li nam ovo dostaviti u DOC-u: https://www.pristupinfo.hr/wp-content/uploads/2018/10/Smjernice-za-proaktivnu-objavu-Otvorena-vlast-i-povjerenje-gra%C4%91ana.pdf

**Comment by schlos** [comment]
Issues are fixed.

Rest is no longer required.
