### ISSUE TITLE
Problem when editing public body

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/imamopravoznati#75]
### Actual behavior

Error 500

```
[ERROR] [imamopravoznati.org] admin_public_body#show (RuntimeError) "internal error, last_event_forming_initial_request ...

A RuntimeError occurred in admin_public_body#show:

  internal error, last_event_forming_initial_request gets nil for request 6248 outgoing messages count 1 all events: --- []

  app/models/info_request.rb:780:in `last_event_forming_initial_request'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/admin/bodies/12941
  * HTTP Method: GET
  * IP address :  
  * Parameters : {"controller"=>"admin_public_body", "action"=>"show", "id"=>"12941"}
  * Timestamp  : 2019-09-10 21:34:32 +0200
  * Server : imamopravoznati
  * Rails root : /var/www/imamopravoznati.org/alaveteli
  * Process: 19790

-------------------------------
Backtrace:
-------------------------------

  app/models/info_request.rb:780:in `last_event_forming_initial_request'
  app/models/info_request.rb:847:in `calculate_date_initial_request_last_sent_at'
  app/models/info_request.rb:841:in `date_initial_request_last_sent_at'
  app/models/concerns/admin_column.rb:15:in `block in for_admin_column'
  app/models/concerns/admin_column.rb:14:in `each'
  app/models/concerns/admin_column.rb:14:in `for_admin_column'
  app/views/admin_request/_some_requests.html.erb:17:in `block in _app_views_admin_request__some_requests_html_erb__2216653242027161637_82901220'
  app/views/admin_request/_some_requests.html.erb:2:in `_app_views_admin_request__some_requests_html_erb__2216653242027161637_82901220'
  app/views/admin_public_body/show.html.erb:97:in `_app_views_admin_public_body_show_html_erb___3932512601620188209_82426080'
  app/controllers/admin_public_body_controller.rb:29:in `block in show'
  lib/alaveteli_localization.rb:43:in `with_locale'
  app/controllers/admin_public_body_controller.rb:20:in `show'
  app/controllers/application_controller.rb:120:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

### Steps to reproduce

1. Go to http://imamopravoznati.org/admin/bodies/12941

### Expected behavior

Should work

**Comment by schlos** [comment]
Reproducible also with http://imamopravoznati.org/admin/bodies/32386

**Comment by schlos** [comment]
Reproducible also with http://imamopravoznati.org/admin/bodies/28575

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28648

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28649

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28657

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28695

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/29109

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28710

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/29008

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/29043

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/28989

**Comment by schlos** [comment]
http://imamopravoznati.org/admin/bodies/29123

**Comment by garethrees** [comment]
Sounds like there are requests made to those authorities that have failed to send. Have a look at https://github.com/mysociety/alaveteli/wiki/Resending-Failed-Outgoing-Messages

**Comment by schlos** [comment]
To verify if message was stuck in sending status:

alaveteli@imamopravoznati:~/alaveteli$ bundle exec rails console
Loading production environment (Rails 4.2.9)
irb(main):001:0> InfoRequest.find(6148).outgoing_messages.first.status
=> "ready"

**Comment by schlos** [comment]
Fixed requests id:

- initial request - resent:
6447
6442
6426
6423
6396
6248
6148
5133
4372
4371
4336
4335
4248
4247
4246
3938
3936

- followup request - resent:



- duplicates - destroyed:
6446
6445
6444
6443
6441
6440
3937

**Comment by schlos** [comment]
All done, final check:

irb(main):949:0> OutgoingMessage.where(:status => 'ready')
=> #<ActiveRecord::Relation [#<OutgoingMessage id: 1, info_request_id: 1, body: "This is the holding pen request. It shows response...", status: "ready", message_type: "initial_request", created_at: "2015-02-21 11:12:31", updated_at: "2015-02-21 11:12:31", last_sent_at: "2015-02-21 11:12:31", incoming_message_followup_id: nil, what_doing: "normal_sort", prominence: "normal", prominence_reason: nil>]>
irb(main):950:0> 

only Holding Pen 👍
